"""
Midnight Season 1 boss manifests.
"""
from __future__ import annotations

from .beloren_child_of_alar import BELOREN_CHILD_OF_ALAR_MANIFEST
from .crown_of_the_cosmos import CROWN_OF_THE_COSMOS_MANIFEST
from .imperator_averzian import IMPERATOR_AVERZIAN_MANIFEST
from .lightblinded_vanguard import LIGHTBLINDED_VANGUARD_MANIFEST
from .midnight_falls import MIDNIGHT_FALLS_MANIFEST
from .vorasius import VORASIUS_MANIFEST

MIDNIGHT_SEASON_1_MANIFESTS = (
    BELOREN_CHILD_OF_ALAR_MANIFEST,
    IMPERATOR_AVERZIAN_MANIFEST,
    LIGHTBLINDED_VANGUARD_MANIFEST,
    VORASIUS_MANIFEST,
    CROWN_OF_THE_COSMOS_MANIFEST,
    MIDNIGHT_FALLS_MANIFEST,
)

__all__ = [
    "BELOREN_CHILD_OF_ALAR_MANIFEST",
    "CROWN_OF_THE_COSMOS_MANIFEST",
    "IMPERATOR_AVERZIAN_MANIFEST",
    "LIGHTBLINDED_VANGUARD_MANIFEST",
    "MIDNIGHT_FALLS_MANIFEST",
    "MIDNIGHT_SEASON_1_MANIFESTS",
    "VORASIUS_MANIFEST",
]
