"""Midnight Season 2 boss manifests."""
from __future__ import annotations

from .entombed_sentinels import ENTOMBED_SENTINELS_HEROIC_MANIFEST
from .nek_zali_the_soulcoiler import (
    NEK_ZALI_THE_SOULCOILER_HEROIC_MANIFEST,
    NEK_ZALI_THE_SOULCOILER_MYTHIC_MANIFEST,
)
from .the_lost_explorers import THE_LOST_EXPLORERS_HEROIC_MANIFEST
from .vashnik_the_malignant import VASHNIK_THE_MALIGNANT_HEROIC_MANIFEST
from .sszorak import SSZORAK_HEROIC_MANIFEST
from .the_twin_fangs import THE_TWIN_FANGS_HEROIC_MANIFEST
from .the_coiled_altar import THE_COILED_ALTAR_HEROIC_MANIFEST
from .ula_tek import ULA_TEK_HEROIC_MANIFEST

MIDNIGHT_SEASON_2_MANIFESTS = (
    NEK_ZALI_THE_SOULCOILER_HEROIC_MANIFEST,
    NEK_ZALI_THE_SOULCOILER_MYTHIC_MANIFEST,
    ENTOMBED_SENTINELS_HEROIC_MANIFEST,
    THE_LOST_EXPLORERS_HEROIC_MANIFEST,
    VASHNIK_THE_MALIGNANT_HEROIC_MANIFEST,
    SSZORAK_HEROIC_MANIFEST,
    THE_TWIN_FANGS_HEROIC_MANIFEST,
    THE_COILED_ALTAR_HEROIC_MANIFEST,
    ULA_TEK_HEROIC_MANIFEST,
)

__all__ = [
    "ENTOMBED_SENTINELS_HEROIC_MANIFEST",
    "MIDNIGHT_SEASON_2_MANIFESTS",
    "NEK_ZALI_THE_SOULCOILER_HEROIC_MANIFEST",
    "NEK_ZALI_THE_SOULCOILER_MYTHIC_MANIFEST",
    "THE_LOST_EXPLORERS_HEROIC_MANIFEST",
    "VASHNIK_THE_MALIGNANT_HEROIC_MANIFEST",
    "SSZORAK_HEROIC_MANIFEST",
    "THE_TWIN_FANGS_HEROIC_MANIFEST",
    "THE_COILED_ALTAR_HEROIC_MANIFEST",
    "ULA_TEK_HEROIC_MANIFEST",
]
